name: 🐛 Bug Report
description: Report an issue that should be fixed
labels:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a bug report, if you have an issue with bun and not this flake [please report over there](https://github.com/oven-sh/bun/issues/new/choose).

  - type: textarea
    attributes: 
      label: "Nix infomation"
      description: "Please run `nix-shell -p nix-info --run \"nix-info -m\"` on a terminal and paste the output of that command here."

  - type: textarea
    attributes: 
      label: "Describe the issue"
      description: "Describe the issue in clear and consise what the issue is"
    validations:
      required: true

  - type: textarea
    atrributes: 
      label: "How to reproduce?"
      description: "Provide the exact step-by-step to reproduce your issue clearly and consise using number bullet points."
    validations:
      required: true

  - type: input
    attributes:
      label: "Expected behaviour"
      description: "A concise description of what was supposed to happen."
    validations:
      required: true


  - type: "textarea"
    attributes:
      label: "Screenshots & logs"
      description: | 
        If applicable, copy and paste any relevant log output or add screenshots to help explain your problem.
        For logs please add backticks and screenshots please [read the github docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#uploading-assets)
  
  - type: checkboxes
    attributes:
      label: "Checklist"
      options: 
        - label: "I am sure this is an issue with this flake and not bun"
          required: true
        - label: "I am sure this issue [hasn't been reported already](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen)"
          required: true
        - label: "I am sure this is not a [question/help needed about this flake](https://github.com/eveeifyeve/bun-flake/discussion/)"

  - type: markdown
    attributes:
      value: | 
        # Thankyou for helping to improve the unoffical bun-flake.

        ---

  - type: textarea
    attributes:
      label: "mention maintainers"
      description: |
        **Please do not edit this!** 

        This is for mentioning maintainers of this flake

      value: "Maintainers: @eveeifyeve"
